version: '3.2'
services:
  nginx-user1:
    image: '10.1.68.41:4443/admin/nginx'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: continue
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: '1000000000'
        reservations:
          cpus: '0.5'
          memory: '500000000'